# NAME: DuetModel
NAME: ReactModel
NUM_LAYERS: 6
NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 512
FF_SIZE: 1024
ACTIVATION: gelu
CHECKPOINT: checkpoints/DEBUG/model/epoch=1499-step=21000.ckpt

DIFFUSION_STEPS: 300
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 200

CONTROL: text
STRATEGY: ddim50
CFG_WEIGHT: 3.5