NAME: DuetModel
NUM_LAYERS: 10

# NAME: ReactModel
# NUM_LAYERS: 20

NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 512
FF_SIZE: 1024
MUSIC_DIM: 4800
ACTIVATION: gelu
CHECKPOINT: /home/verma198/Public/dance/checkpoints/duet20_both_juke/model/model=DuetModel-epoch=99-step=600.ckpt

DIFFUSION_STEPS: 200
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 200

CONTROL: text
STRATEGY: ddim50
CFG_WEIGHT: 3.5

USE_TEXT: True
USE_MOTION: True